//
// Created by hujianzhe
//

#ifndef	UTIL_C_SYSLIB_VKEYCODE_H
#define	UTIL_C_SYSLIB_VKEYCODE_H

#include "../platform_define.h"

#if defined(_WIN32) || defined(_WIN64)
enum {
	VKEY_F1 = VK_F1,
	VKEY_F2 = VK_F2,
	VKEY_F3 = VK_F3,
	VKEY_F4 = VK_F4,
	VKEY_F5 = VK_F5,
	VKEY_F6 = VK_F6,
	VKEY_F7 = VK_F7,
	VKEY_F8 = VK_F8,
	VKEY_F9 = VK_F9,
	VKEY_F10 = VK_F10,
	VKEY_F11 = VK_F11,
	VKEY_F12 = VK_F12,
	VKEY_LBUTTON = VK_LBUTTON,
	VKEY_RBUTTON = VK_RBUTTON,
	VKEY_MBUTTON = VK_MBUTTON,
	VKEY_UP = VK_UP,
	VKEY_DOWN = VK_DOWN,
	VKEY_LEFT = VK_LEFT,
	VKEY_RIGHT = VK_RIGHT,
	VKEY_ENTER = VK_RETURN,
	VKEY_SPACE = VK_SPACE,
	VKEY_TAB = VK_TAB,
	VKEY_PAGEUP = VK_PRIOR,
	VKEY_PAGEDOWN = VK_NEXT,
	VKEY_HOME = VK_HOME,
	VKEY_END = VK_END,
	VKEY_ESC = VK_ESCAPE,
	VKEY_DELETE = VK_DELETE,
	VKEY_INSERT = VK_INSERT,
	VKEY_BACKSPACE = VK_BACK,
	VKEY_SCROLLLOCK = VK_SCROLL,
	VKEY_NUMLOCK = VK_NUMLOCK,
	VKEY_CAPSLOCK = VK_CAPITAL,
	VKEY_CTRL = VK_CONTROL,
	VKEY_ALT = VK_MENU,
	VKEY_SHIFT = VK_SHIFT,
};
#elif	__linux__
#include <linux/input.h>
enum {
	VKEY_F1			= KEY_F1,
	VKEY_F2			= KEY_F2,
	VKEY_F3			= KEY_F3,
	VKEY_F4			= KEY_F4,
	VKEY_F5			= KEY_F5,
	VKEY_F6			= KEY_F6,
	VKEY_F7			= KEY_F7,
	VKEY_F8			= KEY_F8,
	VKEY_F9			= KEY_F9,
	VKEY_F10		= KEY_F10,
	VKEY_F11		= KEY_F11,
	VKEY_F12		= KEY_F12,
	VKEY_LBUTTON	= BTN_LEFT,
	VKEY_RBUTTON	= BTN_RIGHT,
	VKEY_MBUTTON	= BTN_MIDDLE,
	VKEY_UP			= KEY_UP,
	VKEY_DOWN		= KEY_DOWN,
	VKEY_LEFT		= KEY_LEFT,
	VKEY_RIGHT		= KEY_RIGHT,
	VKEY_ENTER		= KEY_ENTER,
	VKEY_SPACE		= KEY_SPACE,
	VKEY_TAB		= KEY_TAB,
	VKEY_PAGEUP		= KEY_PAGEUP,
	VKEY_PAGEDOWN	= KEY_PAGEDOWN,
	VKEY_HOME		= KEY_HOME,
	VKEY_END		= KEY_END,
	VKEY_ESC		= KEY_ESC,
	VKEY_DELETE		= KEY_DELETE,
	VKEY_INSERT 	= KEY_INSERT,
	VKEY_BACKSPACE	= KEY_BACKSPACE,
	VKEY_SCROLLLOCK	= KEY_SCROLLLOCK,
	VKEY_NUMLOCK	= KEY_NUMLOCK,
	VKEY_CAPSLOCK	= KEY_CAPSLOCK,
	VKEY_CTRL		= 0x10000,
	VKEY_ALT		= 0x10001,
	VKEY_SHIFT		= 0x10002,
};
#else
	// TODO MAC

#endif

#endif
